### ISSUE TITLE
Error in prediction(pred, obs) : Number of classes is not equal to 2. 

### ISSUE THREAD

**Issue by nicolerg** [wgmao/DataRemix#1]
Hello, I am getting the following error when I try to run the `corMatToAUC()` function:
```
Error in prediction(pred, obs) : Number of classes is not equal to 2. ROCR currently supports only evaluation of binary classification tasks.
5. stop(message)
4. prediction(pred, obs)
3. auc_pr(y, x)
2. perPathPR(pathPredict, GS)
1. corMatToAUC(corrected_cc, canonical)
```
Do you have any idea what I'm doing wrong? `data` is a 5675x5675 gene-gene correlation matrix from normalized gene expression. `GS` is https://github.com/wgmao/DataRemix/blob/master/inst/extdata/canonical.rdata?raw=true subset down to genes whose gene symbols overlap between my dataset and the `canonical` matrix (5675x1330). `rownames(data) == colnames(data) == rownames(GS)`.

**Comment by nicolerg** [comment]
It looks like this error specifically occurs when the `y`/`obs` parameter for `auc_pr()` has only a single 1 value or if the whole vector is 1 or 0. I will just exclude pathways where this is the case, but perhaps the code or documentation could be updated to handle that case.

**Comment by wgmao** [comment]
You are right. When there is a all-ones vector or all-zeros vector, there will be an error. Thank you for the suggestion. I will update the function to handle this.

**Comment by nicolerg** [comment]
Thank you! I also got the error when there was a single 1. `GS = GS[colSums(GS)>1]` prevented the error.

**Comment by wgmao** [comment]
This bug has been resolved in the latest version. Sorry for the delay.
